/**
 * Core permission keys seeded from docs/reference/permission-catalog.md.
 * Product/shared pack keys are registered later — not inventable at runtime without catalog.
 */
export const CORE_PERMISSION_SEEDS: ReadonlyArray<{
  key: string;
  description: string;
}> = [
  { key: "identity.user.read", description: "View user profile / status (support)" },
  { key: "identity.user.manage", description: "Activate / suspend / deactivate / unlock users" },
  { key: "identity.session.revoke", description: "Force-revoke sessions" },
  {
    key: "identity.external_identity.manage",
    description: "Link/unlink external identities",
  },
  { key: "tenancy.organization.read", description: "View organization profile" },
  { key: "tenancy.organization.manage", description: "Update org settings" },
  { key: "tenancy.location.read", description: "View locations" },
  { key: "tenancy.location.manage", description: "Create/update/deactivate locations" },
  { key: "tenancy.membership.read", description: "List/view memberships" },
  { key: "tenancy.membership.manage", description: "Add/remove/suspend members" },
  { key: "tenancy.invitation.manage", description: "Create/revoke invitations" },
  {
    key: "tenancy.organization.transfer_owner",
    description: "Transfer organization owner",
  },
  { key: "rbac.permission.read", description: "View permission catalog" },
  { key: "rbac.role.read", description: "View roles" },
  { key: "rbac.role.manage", description: "Create/update/delete org roles" },
  { key: "rbac.assignment.manage", description: "Grant/revoke role assignments" },
  { key: "rbac.assignment.read", description: "View assignments" },
  { key: "audit.read", description: "Query audit records" },
  { key: "audit.retention.manage", description: "Trigger archive/purge workflows" },
  { key: "parties.party.read", description: "View parties" },
  { key: "parties.party.manage", description: "Create/update/lifecycle parties" },
  {
    key: "parties.classification.manage",
    description: "Grant/revoke classification role keys",
  },
  { key: "parties.principal.link", description: "Link/unlink Identity principal" },
  {
    key: "parties.relationship.manage",
    description: "Create/remove relationships",
  },
  { key: "parties.party.merge", description: "Merge parties (sensitive)" },
  { key: "catalog.item.read", description: "View catalog items/variants/prices" },
  {
    key: "catalog.item.manage",
    description: "Create/update/lifecycle items, variants, prices",
  },
  { key: "catalog.tax.manage", description: "Manage tax categories" },
  { key: "orders.order.read", description: "View orders" },
  { key: "orders.order.manage", description: "Create/edit draft orders" },
  { key: "orders.order.commit", description: "Commit drafts (commercial commitment)" },
  { key: "orders.order.fulfill", description: "Mark fulfill / partial fulfill" },
  { key: "orders.order.cancel", description: "Cancel orders" },
  { key: "payments.payment.read", description: "View payment intents and outcomes" },
  { key: "payments.payment.create", description: "Create payment intents" },
  { key: "payments.payment.capture", description: "Capture authorized payments" },
  { key: "payments.payment.refund", description: "Refund (sensitive)" },
  { key: "payments.payment.cancel", description: "Cancel payment intents" },
  { key: "ledger.account.read", description: "View chart of accounts" },
  { key: "ledger.account.manage", description: "Create/update accounts" },
  { key: "ledger.journal.read", description: "View journal entries / postings" },
  { key: "ledger.journal.post", description: "Post balanced journals" },
  { key: "ledger.journal.reverse", description: "Reverse posted journals (sensitive)" },
  { key: "inventory.stock.read", description: "View stock balances / movements" },
  { key: "inventory.stock.receive", description: "Post receipts" },
  { key: "inventory.stock.issue", description: "Post issues" },
  { key: "inventory.stock.adjust", description: "Adjustments (sensitive)" },
  { key: "inventory.stock.reserve", description: "Soft-reserve stock" },
  { key: "reporting.read", description: "View reporting projections and reports" },
  { key: "reporting.export", description: "Export reporting datasets" },
  { key: "reporting.kpi.read", description: "View KPI dashboards" },
];

/** Permissions bound to organization.administrator system role. */
export const ORGANIZATION_ADMINISTRATOR_PERMISSIONS: readonly string[] = [
  "tenancy.organization.read",
  "tenancy.organization.manage",
  "tenancy.location.read",
  "tenancy.location.manage",
  "tenancy.membership.read",
  "tenancy.membership.manage",
  "tenancy.invitation.manage",
  "tenancy.organization.transfer_owner",
  "rbac.permission.read",
  "rbac.role.read",
  "rbac.role.manage",
  "rbac.assignment.manage",
  "rbac.assignment.read",
  "audit.read",
  "parties.party.read",
  "parties.party.manage",
  "parties.classification.manage",
  "parties.principal.link",
  "parties.relationship.manage",
  "parties.party.merge",
  "catalog.item.read",
  "catalog.item.manage",
  "catalog.tax.manage",
  "orders.order.read",
  "orders.order.manage",
  "orders.order.commit",
  "orders.order.fulfill",
  "orders.order.cancel",
  "payments.payment.read",
  "payments.payment.create",
  "payments.payment.capture",
  "payments.payment.refund",
  "payments.payment.cancel",
  "ledger.account.read",
  "ledger.account.manage",
  "ledger.journal.read",
  "ledger.journal.post",
  "ledger.journal.reverse",
  "inventory.stock.read",
  "inventory.stock.receive",
  "inventory.stock.issue",
  "inventory.stock.adjust",
  "inventory.stock.reserve",
  "reporting.read",
  "reporting.export",
  "reporting.kpi.read",
];
